source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.1'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'docker-api'

group :development, :test do
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'better_errors'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'annotate'
  gem 'listen', '~> 3.0.5'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
